apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv1
  labels:
    type: aws-pv1
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0940dca772cfcf8cd
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv2
  labels:
    type: aws-pv2
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0fe5b2a3bba457d77
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv3
  labels:
    type: aws-pv3
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 6Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0807c0129f0ba368b
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv4
  labels:
    type: aws-pv4
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-03e01d90989cbf9d3
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv5
  labels:
    type: aws-pv5
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0ca39f5e0eccff3bd
    fsType: ext4





# aws ec2 create-volume --volume-type gp2 --size 2 --availability-zone ap-south-1a --tag-specifications 'ResourceType=volume,Tags=[{Key=KubernetesCluster,Value=chaitanya.xyz},{Key=Name,Value=aws-pv1}]' && aws ec2 create-volume --volume-type gp2 --size 4 --availability-zone ap-south-1a --tag-specifications 'ResourceType=volume,Tags=[{Key=KubernetesCluster,Value=chaitanya.xyz},{Key=Name,Value=aws-pv2}]' && aws ec2 create-volume --volume-type gp2 --size 6 --availability-zone ap-south-1a --tag-specifications 'ResourceType=volume,Tags=[{Key=KubernetesCluster,Value=chaitanya.xyz},{Key=Name,Value=aws-pv3}]' && aws ec2 create-volume --volume-type gp2 --size 8 --availability-zone ap-south-1a --tag-specifications 'ResourceType=volume,Tags=[{Key=KubernetesCluster,Value=chaitanya.xyz},{Key=Name,Value=aws-pv4}]' && aws ec2 create-volume --volume-type gp2 --size 10 --availability-zone ap-south-1a --tag-specifications 'ResourceType=volume,Tags=[{Key=KubernetesCluster,Value=chaitanya.xyz},{Key=Name,Value=aws-pv5}]'
