apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: XXXXXXXXXXX
      server: https://api.cloudvishwakarma.in
      tls-server-name: api.internal.cloudvishwakarma.in
    name: cloudvishwakarma.in
contexts:
  - context:
      cluster: cloudvishwakarma.in
      namespace: development
      user: user1
    name: user1-context
current-context: user1-context
kind: Config
users:
  - name: user1
    user:
      client-certificate: /root/user1.crt
      client-key: /root/user1.key

---
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0N3SEtuV0FFKytDY3RreU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TXpFd01UQXlNelUxV2hjTk16VXdNekV3TVRBeQpNelUxV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBeFduNi9Lem9LUVE3VWs5L1c1QW41Mm9qak5FVDRaZWc4RW8zakZ6bWwzS0MKeHUxYzV0TFptSVNIMWVzVDh1MVl1YXUrVml4RkZzemVHcEJWUktiTW1aN1RQZ2xITlJ3dTNvUm1UU3NRUGJYVgpmQVZDRE13blNGakJ6S1VLZGFPQ0xVcWNpQ1lhUWlyazljdWZZTFZkMXRXeTZFUFN5MjhxRzYvdG9LS00yZk9vCkNXVjNIMEQvcTJKZnNlaEtEQnM5cWphWU9Qa3hiZ25sRno5VVBHaVYzNnNmdFg1NTB0aDZNaS9KeEM2My9UbXIKd0E4SVVrY2pPa2xQWTJXUjNnMkN4Ym1ISURlQi9nazJnVm9YUnFXNW04TXRFT2lLNlZvbkNaV2d4T2RsZ2VNWApJNnFkQjYza2kzczd3YmQ3R1VTOHVmcWRBOWwzOWx3T2VpUmNpZDNCQlFJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUFlR3RKRTd2RFMyRHIwT3AKRmtNWkdRalRmSUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUs3ZUZtZGxwTDRJYWVNU2MyNm91NFZMTDdsagpVNDNBdHdjTVlPOEdadzh5ZWhwSVdZYkxzNElFRjZUMTFNbEVucDRkd2w4YzNocEt1Z1JJMGhsNHdmN2pydEdzCjM2VHVWNWM2K3B4MlNFcFNKV1l2MFg5OG5TRi85eGxGUTg2eG54R05YaFozZ1B2QVdJLytGdGVUYWFwR1UxcFcKVGtCUVFtaVdoSzhOVWxXVjlpaGVXZjJZSzRNdzhYMFAyMXZqM3owVzZhbmFFbndITnk4V1YxU3VTbUpQay9uMQpLUVJsakVxOXlPeWY1eHhQVzlEVUVzWjdVVTZEZS8waUtvZGlZejlGeFhiQUdBNWc4N0RCQkRJOGtiTThOUHRiCmdKdmNJUzFDZlJpSXcrQmE5RDdDTXJVbHp1bkhsckpDVXlOdkFLSVFFNUdUM1FqQVA4d2hUQ202ajBNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api-chaitanya-xyz-as2pvo-c075e1fd2270f1fe.elb.ap-south-1.amazonaws.com
    tls-server-name: api.internal.chaitanya.xyz
  name: chaitanya.xyz
contexts:
- context:
    cluster: chaitanya.xyz
    namespace: development
    user: chaitanya
  name: chaitanya-context
current-context: chaitanya-context
kind: Config
preferences: {}
users:
- name: chaitanya
  user:
    client-certificate: /root/chaitanya.crt
    client-key: /root/chaitanya.key


---
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0N3SEtuV0FFKytDY3RreU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TXpFd01UQXlNelUxV2hjTk16VXdNekV3TVRBeQpNelUxV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBeFduNi9Lem9LUVE3VWs5L1c1QW41Mm9qak5FVDRaZWc4RW8zakZ6bWwzS0MKeHUxYzV0TFptSVNIMWVzVDh1MVl1YXUrVml4RkZzemVHcEJWUktiTW1aN1RQZ2xITlJ3dTNvUm1UU3NRUGJYVgpmQVZDRE13blNGakJ6S1VLZGFPQ0xVcWNpQ1lhUWlyazljdWZZTFZkMXRXeTZFUFN5MjhxRzYvdG9LS00yZk9vCkNXVjNIMEQvcTJKZnNlaEtEQnM5cWphWU9Qa3hiZ25sRno5VVBHaVYzNnNmdFg1NTB0aDZNaS9KeEM2My9UbXIKd0E4SVVrY2pPa2xQWTJXUjNnMkN4Ym1ISURlQi9nazJnVm9YUnFXNW04TXRFT2lLNlZvbkNaV2d4T2RsZ2VNWApJNnFkQjYza2kzczd3YmQ3R1VTOHVmcWRBOWwzOWx3T2VpUmNpZDNCQlFJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUFlR3RKRTd2RFMyRHIwT3AKRmtNWkdRalRmSUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUs3ZUZtZGxwTDRJYWVNU2MyNm91NFZMTDdsagpVNDNBdHdjTVlPOEdadzh5ZWhwSVdZYkxzNElFRjZUMTFNbEVucDRkd2w4YzNocEt1Z1JJMGhsNHdmN2pydEdzCjM2VHVWNWM2K3B4MlNFcFNKV1l2MFg5OG5TRi85eGxGUTg2eG54R05YaFozZ1B2QVdJLytGdGVUYWFwR1UxcFcKVGtCUVFtaVdoSzhOVWxXVjlpaGVXZjJZSzRNdzhYMFAyMXZqM3owVzZhbmFFbndITnk4V1YxU3VTbUpQay9uMQpLUVJsakVxOXlPeWY1eHhQVzlEVUVzWjdVVTZEZS8waUtvZGlZejlGeFhiQUdBNWc4N0RCQkRJOGtiTThOUHRiCmdKdmNJUzFDZlJpSXcrQmE5RDdDTXJVbHp1bkhsckpDVXlOdkFLSVFFNUdUM1FqQVA4d2hUQ202ajBNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api-chaitanya-xyz-as2pvo-c075e1fd2270f1fe.elb.ap-south-1.amazonaws.com
    tls-server-name: api.internal.chaitanya.xyz
  name: chaitanya.xyz
contexts:
- context:
    cluster: chaitanya.xyz
    namespace: production
    user: rama
  name: rama-context
current-context: rama-context
kind: Config
preferences: {}
users:
- name: rama
  user:
    client-certificate: /root/rama.crt
    client-key: /root/rama.key


---
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0N3SEtuV0FFKytDY3RreU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TXpFd01UQXlNelUxV2hjTk16VXdNekV3TVRBeQpNelUxV2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBeFduNi9Lem9LUVE3VWs5L1c1QW41Mm9qak5FVDRaZWc4RW8zakZ6bWwzS0MKeHUxYzV0TFptSVNIMWVzVDh1MVl1YXUrVml4RkZzemVHcEJWUktiTW1aN1RQZ2xITlJ3dTNvUm1UU3NRUGJYVgpmQVZDRE13blNGakJ6S1VLZGFPQ0xVcWNpQ1lhUWlyazljdWZZTFZkMXRXeTZFUFN5MjhxRzYvdG9LS00yZk9vCkNXVjNIMEQvcTJKZnNlaEtEQnM5cWphWU9Qa3hiZ25sRno5VVBHaVYzNnNmdFg1NTB0aDZNaS9KeEM2My9UbXIKd0E4SVVrY2pPa2xQWTJXUjNnMkN4Ym1ISURlQi9nazJnVm9YUnFXNW04TXRFT2lLNlZvbkNaV2d4T2RsZ2VNWApJNnFkQjYza2kzczd3YmQ3R1VTOHVmcWRBOWwzOWx3T2VpUmNpZDNCQlFJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUFlR3RKRTd2RFMyRHIwT3AKRmtNWkdRalRmSUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUs3ZUZtZGxwTDRJYWVNU2MyNm91NFZMTDdsagpVNDNBdHdjTVlPOEdadzh5ZWhwSVdZYkxzNElFRjZUMTFNbEVucDRkd2w4YzNocEt1Z1JJMGhsNHdmN2pydEdzCjM2VHVWNWM2K3B4MlNFcFNKV1l2MFg5OG5TRi85eGxGUTg2eG54R05YaFozZ1B2QVdJLytGdGVUYWFwR1UxcFcKVGtCUVFtaVdoSzhOVWxXVjlpaGVXZjJZSzRNdzhYMFAyMXZqM3owVzZhbmFFbndITnk4V1YxU3VTbUpQay9uMQpLUVJsakVxOXlPeWY1eHhQVzlEVUVzWjdVVTZEZS8waUtvZGlZejlGeFhiQUdBNWc4N0RCQkRJOGtiTThOUHRiCmdKdmNJUzFDZlJpSXcrQmE5RDdDTXJVbHp1bkhsckpDVXlOdkFLSVFFNUdUM1FqQVA4d2hUQ202ajBNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api-chaitanya-xyz-as2pvo-c075e1fd2270f1fe.elb.ap-south-1.amazonaws.com
    tls-server-name: api.internal.chaitanya.xyz
  name: chaitanya.xyz
contexts:
- context:
    cluster: chaitanya.xyz
    namespace: production
    user: saikiran
  name: saikiran-context
current-context: saikiran-context
kind: Config
preferences: {}
users:
- name: saikiran
  user:
    client-certificate: /root/saikiran.crt
    client-key: /root/saikiran.key