kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaitanya-RoleBinding
  namespace: development
subjects:
- kind: User
  name: chaitanya
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: chaitanya-role
  apiGroup: rbac.authorization.k8s.io 

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rama-RoleBinding
  namespace: production
subjects:
- kind: User
  name: rama
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: rama-role
  apiGroup: rbac.authorization.k8s.io 



